/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as WatchWorkRouteImport } from './routes/watch.$work'
import { Route as PrototypesXialiaoDeskRouteImport } from './routes/prototypes.xialiao-desk'
import { Route as AppPaymentReturnRouteImport } from './routes/_app/payment-return'
import { Route as AppCreditsRouteImport } from './routes/_app/credits'
import { Route as AppAccessUnavailableRouteImport } from './routes/_app/access-unavailable'
import { Route as AppProjectsProjectTasksRouteImport } from './routes/_app/projects.$project/tasks'
import { Route as AppProjectsProjectStylesRouteImport } from './routes/_app/projects.$project/styles'
import { Route as AppProjectsProjectIngestRouteImport } from './routes/_app/projects.$project/ingest'
import { Route as AppProjectsProjectEpisodesRouteImport } from './routes/_app/projects.$project/episodes'
import { Route as AppProjectsProjectAssistantRouteImport } from './routes/_app/projects.$project/assistant'

const DownloadLazyRouteImport = createFileRoute('/download')()
const AppProjectsProjectFreezoneLazyRouteImport = createFileRoute(
  '/_app/projects/$project/freezone',
)()
const AppProjectsProjectCharactersLazyRouteImport = createFileRoute(
  '/_app/projects/$project/characters',
)()
const AppProjectsProjectEpisodesEpisodeIndexLazyRouteImport = createFileRoute(
  '/_app/projects/$project/episodes/$episode/',
)()
const AppProjectsProjectEpisodesEpisodeVideoLazyRouteImport = createFileRoute(
  '/_app/projects/$project/episodes/$episode/video',
)()
const AppProjectsProjectEpisodesEpisodeSketchesLazyRouteImport =
  createFileRoute('/_app/projects/$project/episodes/$episode/sketches')()
const AppProjectsProjectEpisodesEpisodeScriptLazyRouteImport = createFileRoute(
  '/_app/projects/$project/episodes/$episode/script',
)()
const AppProjectsProjectEpisodesEpisodeOverviewLazyRouteImport =
  createFileRoute('/_app/projects/$project/episodes/$episode/overview')()
const AppProjectsProjectEpisodesEpisodeComposeLazyRouteImport = createFileRoute(
  '/_app/projects/$project/episodes/$episode/compose',
)()
const AppProjectsProjectEpisodesEpisodeBeatsLazyRouteImport = createFileRoute(
  '/_app/projects/$project/episodes/$episode/beats',
)()
const AppProjectsProjectEpisodesEpisodeAudioLazyRouteImport = createFileRoute(
  '/_app/projects/$project/episodes/$episode/audio',
)()

const DownloadLazyRoute = DownloadLazyRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/download.lazy').then((d) => d.Route))
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const WatchWorkRoute = WatchWorkRouteImport.update({
  id: '/watch/$work',
  path: '/watch/$work',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypesXialiaoDeskRoute = PrototypesXialiaoDeskRouteImport.update({
  id: '/prototypes/xialiao-desk',
  path: '/prototypes/xialiao-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPaymentReturnRoute = AppPaymentReturnRouteImport.update({
  id: '/payment-return',
  path: '/payment-return',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessUnavailableRoute = AppAccessUnavailableRouteImport.update({
  id: '/access-unavailable',
  path: '/access-unavailable',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectFreezoneLazyRoute =
  AppProjectsProjectFreezoneLazyRouteImport.update({
    id: '/projects/$project/freezone',
    path: '/projects/$project/freezone',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/freezone.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectCharactersLazyRoute =
  AppProjectsProjectCharactersLazyRouteImport.update({
    id: '/projects/$project/characters',
    path: '/projects/$project/characters',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/characters.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectTasksRoute = AppProjectsProjectTasksRouteImport.update({
  id: '/projects/$project/tasks',
  path: '/projects/$project/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectStylesRoute =
  AppProjectsProjectStylesRouteImport.update({
    id: '/projects/$project/styles',
    path: '/projects/$project/styles',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIngestRoute =
  AppProjectsProjectIngestRouteImport.update({
    id: '/projects/$project/ingest',
    path: '/projects/$project/ingest',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectEpisodesRoute =
  AppProjectsProjectEpisodesRouteImport.update({
    id: '/projects/$project/episodes',
    path: '/projects/$project/episodes',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectAssistantRoute =
  AppProjectsProjectAssistantRouteImport.update({
    id: '/projects/$project/assistant',
    path: '/projects/$project/assistant',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectEpisodesEpisodeIndexLazyRoute =
  AppProjectsProjectEpisodesEpisodeIndexLazyRouteImport.update({
    id: '/$episode/',
    path: '/$episode/',
    getParentRoute: () => AppProjectsProjectEpisodesRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/episodes.$episode/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectEpisodesEpisodeVideoLazyRoute =
  AppProjectsProjectEpisodesEpisodeVideoLazyRouteImport.update({
    id: '/$episode/video',
    path: '/$episode/video',
    getParentRoute: () => AppProjectsProjectEpisodesRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/episodes.$episode/video.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectEpisodesEpisodeSketchesLazyRoute =
  AppProjectsProjectEpisodesEpisodeSketchesLazyRouteImport.update({
    id: '/$episode/sketches',
    path: '/$episode/sketches',
    getParentRoute: () => AppProjectsProjectEpisodesRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/episodes.$episode/sketches.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectEpisodesEpisodeScriptLazyRoute =
  AppProjectsProjectEpisodesEpisodeScriptLazyRouteImport.update({
    id: '/$episode/script',
    path: '/$episode/script',
    getParentRoute: () => AppProjectsProjectEpisodesRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/episodes.$episode/script.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectEpisodesEpisodeOverviewLazyRoute =
  AppProjectsProjectEpisodesEpisodeOverviewLazyRouteImport.update({
    id: '/$episode/overview',
    path: '/$episode/overview',
    getParentRoute: () => AppProjectsProjectEpisodesRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/episodes.$episode/overview.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectEpisodesEpisodeComposeLazyRoute =
  AppProjectsProjectEpisodesEpisodeComposeLazyRouteImport.update({
    id: '/$episode/compose',
    path: '/$episode/compose',
    getParentRoute: () => AppProjectsProjectEpisodesRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/episodes.$episode/compose.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectEpisodesEpisodeBeatsLazyRoute =
  AppProjectsProjectEpisodesEpisodeBeatsLazyRouteImport.update({
    id: '/$episode/beats',
    path: '/$episode/beats',
    getParentRoute: () => AppProjectsProjectEpisodesRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/episodes.$episode/beats.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectEpisodesEpisodeAudioLazyRoute =
  AppProjectsProjectEpisodesEpisodeAudioLazyRouteImport.update({
    id: '/$episode/audio',
    path: '/$episode/audio',
    getParentRoute: () => AppProjectsProjectEpisodesRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects.$project/episodes.$episode/audio.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/recharge': typeof RechargeRoute
  '/download': typeof DownloadLazyRoute
  '/access-unavailable': typeof AppAccessUnavailableRoute
  '/credits': typeof AppCreditsRoute
  '/payment-return': typeof AppPaymentReturnRoute
  '/prototypes/xialiao-desk': typeof PrototypesXialiaoDeskRoute
  '/watch/$work': typeof WatchWorkRoute
  '/projects/$project/assistant': typeof AppProjectsProjectAssistantRoute
  '/projects/$project/episodes': typeof AppProjectsProjectEpisodesRouteWithChildren
  '/projects/$project/ingest': typeof AppProjectsProjectIngestRoute
  '/projects/$project/styles': typeof AppProjectsProjectStylesRoute
  '/projects/$project/tasks': typeof AppProjectsProjectTasksRoute
  '/projects/$project/characters': typeof AppProjectsProjectCharactersLazyRoute
  '/projects/$project/freezone': typeof AppProjectsProjectFreezoneLazyRoute
  '/projects/$project/episodes/$episode/audio': typeof AppProjectsProjectEpisodesEpisodeAudioLazyRoute
  '/projects/$project/episodes/$episode/beats': typeof AppProjectsProjectEpisodesEpisodeBeatsLazyRoute
  '/projects/$project/episodes/$episode/compose': typeof AppProjectsProjectEpisodesEpisodeComposeLazyRoute
  '/projects/$project/episodes/$episode/overview': typeof AppProjectsProjectEpisodesEpisodeOverviewLazyRoute
  '/projects/$project/episodes/$episode/script': typeof AppProjectsProjectEpisodesEpisodeScriptLazyRoute
  '/projects/$project/episodes/$episode/sketches': typeof AppProjectsProjectEpisodesEpisodeSketchesLazyRoute
  '/projects/$project/episodes/$episode/video': typeof AppProjectsProjectEpisodesEpisodeVideoLazyRoute
  '/projects/$project/episodes/$episode/': typeof AppProjectsProjectEpisodesEpisodeIndexLazyRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/recharge': typeof RechargeRoute
  '/download': typeof DownloadLazyRoute
  '/access-unavailable': typeof AppAccessUnavailableRoute
  '/credits': typeof AppCreditsRoute
  '/payment-return': typeof AppPaymentReturnRoute
  '/prototypes/xialiao-desk': typeof PrototypesXialiaoDeskRoute
  '/watch/$work': typeof WatchWorkRoute
  '/': typeof AppIndexRoute
  '/projects/$project/assistant': typeof AppProjectsProjectAssistantRoute
  '/projects/$project/episodes': typeof AppProjectsProjectEpisodesRouteWithChildren
  '/projects/$project/ingest': typeof AppProjectsProjectIngestRoute
  '/projects/$project/styles': typeof AppProjectsProjectStylesRoute
  '/projects/$project/tasks': typeof AppProjectsProjectTasksRoute
  '/projects/$project/characters': typeof AppProjectsProjectCharactersLazyRoute
  '/projects/$project/freezone': typeof AppProjectsProjectFreezoneLazyRoute
  '/projects/$project/episodes/$episode/audio': typeof AppProjectsProjectEpisodesEpisodeAudioLazyRoute
  '/projects/$project/episodes/$episode/beats': typeof AppProjectsProjectEpisodesEpisodeBeatsLazyRoute
  '/projects/$project/episodes/$episode/compose': typeof AppProjectsProjectEpisodesEpisodeComposeLazyRoute
  '/projects/$project/episodes/$episode/overview': typeof AppProjectsProjectEpisodesEpisodeOverviewLazyRoute
  '/projects/$project/episodes/$episode/script': typeof AppProjectsProjectEpisodesEpisodeScriptLazyRoute
  '/projects/$project/episodes/$episode/sketches': typeof AppProjectsProjectEpisodesEpisodeSketchesLazyRoute
  '/projects/$project/episodes/$episode/video': typeof AppProjectsProjectEpisodesEpisodeVideoLazyRoute
  '/projects/$project/episodes/$episode': typeof AppProjectsProjectEpisodesEpisodeIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/recharge': typeof RechargeRoute
  '/download': typeof DownloadLazyRoute
  '/_app/access-unavailable': typeof AppAccessUnavailableRoute
  '/_app/credits': typeof AppCreditsRoute
  '/_app/payment-return': typeof AppPaymentReturnRoute
  '/prototypes/xialiao-desk': typeof PrototypesXialiaoDeskRoute
  '/watch/$work': typeof WatchWorkRoute
  '/_app/': typeof AppIndexRoute
  '/_app/projects/$project/assistant': typeof AppProjectsProjectAssistantRoute
  '/_app/projects/$project/episodes': typeof AppProjectsProjectEpisodesRouteWithChildren
  '/_app/projects/$project/ingest': typeof AppProjectsProjectIngestRoute
  '/_app/projects/$project/styles': typeof AppProjectsProjectStylesRoute
  '/_app/projects/$project/tasks': typeof AppProjectsProjectTasksRoute
  '/_app/projects/$project/characters': typeof AppProjectsProjectCharactersLazyRoute
  '/_app/projects/$project/freezone': typeof AppProjectsProjectFreezoneLazyRoute
  '/_app/projects/$project/episodes/$episode/audio': typeof AppProjectsProjectEpisodesEpisodeAudioLazyRoute
  '/_app/projects/$project/episodes/$episode/beats': typeof AppProjectsProjectEpisodesEpisodeBeatsLazyRoute
  '/_app/projects/$project/episodes/$episode/compose': typeof AppProjectsProjectEpisodesEpisodeComposeLazyRoute
  '/_app/projects/$project/episodes/$episode/overview': typeof AppProjectsProjectEpisodesEpisodeOverviewLazyRoute
  '/_app/projects/$project/episodes/$episode/script': typeof AppProjectsProjectEpisodesEpisodeScriptLazyRoute
  '/_app/projects/$project/episodes/$episode/sketches': typeof AppProjectsProjectEpisodesEpisodeSketchesLazyRoute
  '/_app/projects/$project/episodes/$episode/video': typeof AppProjectsProjectEpisodesEpisodeVideoLazyRoute
  '/_app/projects/$project/episodes/$episode/': typeof AppProjectsProjectEpisodesEpisodeIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/recharge'
    | '/download'
    | '/access-unavailable'
    | '/credits'
    | '/payment-return'
    | '/prototypes/xialiao-desk'
    | '/watch/$work'
    | '/projects/$project/assistant'
    | '/projects/$project/episodes'
    | '/projects/$project/ingest'
    | '/projects/$project/styles'
    | '/projects/$project/tasks'
    | '/projects/$project/characters'
    | '/projects/$project/freezone'
    | '/projects/$project/episodes/$episode/audio'
    | '/projects/$project/episodes/$episode/beats'
    | '/projects/$project/episodes/$episode/compose'
    | '/projects/$project/episodes/$episode/overview'
    | '/projects/$project/episodes/$episode/script'
    | '/projects/$project/episodes/$episode/sketches'
    | '/projects/$project/episodes/$episode/video'
    | '/projects/$project/episodes/$episode/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/login'
    | '/recharge'
    | '/download'
    | '/access-unavailable'
    | '/credits'
    | '/payment-return'
    | '/prototypes/xialiao-desk'
    | '/watch/$work'
    | '/'
    | '/projects/$project/assistant'
    | '/projects/$project/episodes'
    | '/projects/$project/ingest'
    | '/projects/$project/styles'
    | '/projects/$project/tasks'
    | '/projects/$project/characters'
    | '/projects/$project/freezone'
    | '/projects/$project/episodes/$episode/audio'
    | '/projects/$project/episodes/$episode/beats'
    | '/projects/$project/episodes/$episode/compose'
    | '/projects/$project/episodes/$episode/overview'
    | '/projects/$project/episodes/$episode/script'
    | '/projects/$project/episodes/$episode/sketches'
    | '/projects/$project/episodes/$episode/video'
    | '/projects/$project/episodes/$episode'
  id:
    | '__root__'
    | '/_app'
    | '/checkout'
    | '/login'
    | '/recharge'
    | '/download'
    | '/_app/access-unavailable'
    | '/_app/credits'
    | '/_app/payment-return'
    | '/prototypes/xialiao-desk'
    | '/watch/$work'
    | '/_app/'
    | '/_app/projects/$project/assistant'
    | '/_app/projects/$project/episodes'
    | '/_app/projects/$project/ingest'
    | '/_app/projects/$project/styles'
    | '/_app/projects/$project/tasks'
    | '/_app/projects/$project/characters'
    | '/_app/projects/$project/freezone'
    | '/_app/projects/$project/episodes/$episode/audio'
    | '/_app/projects/$project/episodes/$episode/beats'
    | '/_app/projects/$project/episodes/$episode/compose'
    | '/_app/projects/$project/episodes/$episode/overview'
    | '/_app/projects/$project/episodes/$episode/script'
    | '/_app/projects/$project/episodes/$episode/sketches'
    | '/_app/projects/$project/episodes/$episode/video'
    | '/_app/projects/$project/episodes/$episode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  RechargeRoute: typeof RechargeRoute
  DownloadLazyRoute: typeof DownloadLazyRoute
  PrototypesXialiaoDeskRoute: typeof PrototypesXialiaoDeskRoute
  WatchWorkRoute: typeof WatchWorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/watch/$work': {
      id: '/watch/$work'
      path: '/watch/$work'
      fullPath: '/watch/$work'
      preLoaderRoute: typeof WatchWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypes/xialiao-desk': {
      id: '/prototypes/xialiao-desk'
      path: '/prototypes/xialiao-desk'
      fullPath: '/prototypes/xialiao-desk'
      preLoaderRoute: typeof PrototypesXialiaoDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/payment-return': {
      id: '/_app/payment-return'
      path: '/payment-return'
      fullPath: '/payment-return'
      preLoaderRoute: typeof AppPaymentReturnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credits': {
      id: '/_app/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access-unavailable': {
      id: '/_app/access-unavailable'
      path: '/access-unavailable'
      fullPath: '/access-unavailable'
      preLoaderRoute: typeof AppAccessUnavailableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/freezone': {
      id: '/_app/projects/$project/freezone'
      path: '/projects/$project/freezone'
      fullPath: '/projects/$project/freezone'
      preLoaderRoute: typeof AppProjectsProjectFreezoneLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/characters': {
      id: '/_app/projects/$project/characters'
      path: '/projects/$project/characters'
      fullPath: '/projects/$project/characters'
      preLoaderRoute: typeof AppProjectsProjectCharactersLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/tasks': {
      id: '/_app/projects/$project/tasks'
      path: '/projects/$project/tasks'
      fullPath: '/projects/$project/tasks'
      preLoaderRoute: typeof AppProjectsProjectTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/styles': {
      id: '/_app/projects/$project/styles'
      path: '/projects/$project/styles'
      fullPath: '/projects/$project/styles'
      preLoaderRoute: typeof AppProjectsProjectStylesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/ingest': {
      id: '/_app/projects/$project/ingest'
      path: '/projects/$project/ingest'
      fullPath: '/projects/$project/ingest'
      preLoaderRoute: typeof AppProjectsProjectIngestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/episodes': {
      id: '/_app/projects/$project/episodes'
      path: '/projects/$project/episodes'
      fullPath: '/projects/$project/episodes'
      preLoaderRoute: typeof AppProjectsProjectEpisodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/assistant': {
      id: '/_app/projects/$project/assistant'
      path: '/projects/$project/assistant'
      fullPath: '/projects/$project/assistant'
      preLoaderRoute: typeof AppProjectsProjectAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/episodes/$episode/': {
      id: '/_app/projects/$project/episodes/$episode/'
      path: '/$episode'
      fullPath: '/projects/$project/episodes/$episode/'
      preLoaderRoute: typeof AppProjectsProjectEpisodesEpisodeIndexLazyRouteImport
      parentRoute: typeof AppProjectsProjectEpisodesRoute
    }
    '/_app/projects/$project/episodes/$episode/video': {
      id: '/_app/projects/$project/episodes/$episode/video'
      path: '/$episode/video'
      fullPath: '/projects/$project/episodes/$episode/video'
      preLoaderRoute: typeof AppProjectsProjectEpisodesEpisodeVideoLazyRouteImport
      parentRoute: typeof AppProjectsProjectEpisodesRoute
    }
    '/_app/projects/$project/episodes/$episode/sketches': {
      id: '/_app/projects/$project/episodes/$episode/sketches'
      path: '/$episode/sketches'
      fullPath: '/projects/$project/episodes/$episode/sketches'
      preLoaderRoute: typeof AppProjectsProjectEpisodesEpisodeSketchesLazyRouteImport
      parentRoute: typeof AppProjectsProjectEpisodesRoute
    }
    '/_app/projects/$project/episodes/$episode/script': {
      id: '/_app/projects/$project/episodes/$episode/script'
      path: '/$episode/script'
      fullPath: '/projects/$project/episodes/$episode/script'
      preLoaderRoute: typeof AppProjectsProjectEpisodesEpisodeScriptLazyRouteImport
      parentRoute: typeof AppProjectsProjectEpisodesRoute
    }
    '/_app/projects/$project/episodes/$episode/overview': {
      id: '/_app/projects/$project/episodes/$episode/overview'
      path: '/$episode/overview'
      fullPath: '/projects/$project/episodes/$episode/overview'
      preLoaderRoute: typeof AppProjectsProjectEpisodesEpisodeOverviewLazyRouteImport
      parentRoute: typeof AppProjectsProjectEpisodesRoute
    }
    '/_app/projects/$project/episodes/$episode/compose': {
      id: '/_app/projects/$project/episodes/$episode/compose'
      path: '/$episode/compose'
      fullPath: '/projects/$project/episodes/$episode/compose'
      preLoaderRoute: typeof AppProjectsProjectEpisodesEpisodeComposeLazyRouteImport
      parentRoute: typeof AppProjectsProjectEpisodesRoute
    }
    '/_app/projects/$project/episodes/$episode/beats': {
      id: '/_app/projects/$project/episodes/$episode/beats'
      path: '/$episode/beats'
      fullPath: '/projects/$project/episodes/$episode/beats'
      preLoaderRoute: typeof AppProjectsProjectEpisodesEpisodeBeatsLazyRouteImport
      parentRoute: typeof AppProjectsProjectEpisodesRoute
    }
    '/_app/projects/$project/episodes/$episode/audio': {
      id: '/_app/projects/$project/episodes/$episode/audio'
      path: '/$episode/audio'
      fullPath: '/projects/$project/episodes/$episode/audio'
      preLoaderRoute: typeof AppProjectsProjectEpisodesEpisodeAudioLazyRouteImport
      parentRoute: typeof AppProjectsProjectEpisodesRoute
    }
  }
}

interface AppProjectsProjectEpisodesRouteChildren {
  AppProjectsProjectEpisodesEpisodeAudioLazyRoute: typeof AppProjectsProjectEpisodesEpisodeAudioLazyRoute
  AppProjectsProjectEpisodesEpisodeBeatsLazyRoute: typeof AppProjectsProjectEpisodesEpisodeBeatsLazyRoute
  AppProjectsProjectEpisodesEpisodeComposeLazyRoute: typeof AppProjectsProjectEpisodesEpisodeComposeLazyRoute
  AppProjectsProjectEpisodesEpisodeOverviewLazyRoute: typeof AppProjectsProjectEpisodesEpisodeOverviewLazyRoute
  AppProjectsProjectEpisodesEpisodeScriptLazyRoute: typeof AppProjectsProjectEpisodesEpisodeScriptLazyRoute
  AppProjectsProjectEpisodesEpisodeSketchesLazyRoute: typeof AppProjectsProjectEpisodesEpisodeSketchesLazyRoute
  AppProjectsProjectEpisodesEpisodeVideoLazyRoute: typeof AppProjectsProjectEpisodesEpisodeVideoLazyRoute
  AppProjectsProjectEpisodesEpisodeIndexLazyRoute: typeof AppProjectsProjectEpisodesEpisodeIndexLazyRoute
}

const AppProjectsProjectEpisodesRouteChildren: AppProjectsProjectEpisodesRouteChildren =
  {
    AppProjectsProjectEpisodesEpisodeAudioLazyRoute:
      AppProjectsProjectEpisodesEpisodeAudioLazyRoute,
    AppProjectsProjectEpisodesEpisodeBeatsLazyRoute:
      AppProjectsProjectEpisodesEpisodeBeatsLazyRoute,
    AppProjectsProjectEpisodesEpisodeComposeLazyRoute:
      AppProjectsProjectEpisodesEpisodeComposeLazyRoute,
    AppProjectsProjectEpisodesEpisodeOverviewLazyRoute:
      AppProjectsProjectEpisodesEpisodeOverviewLazyRoute,
    AppProjectsProjectEpisodesEpisodeScriptLazyRoute:
      AppProjectsProjectEpisodesEpisodeScriptLazyRoute,
    AppProjectsProjectEpisodesEpisodeSketchesLazyRoute:
      AppProjectsProjectEpisodesEpisodeSketchesLazyRoute,
    AppProjectsProjectEpisodesEpisodeVideoLazyRoute:
      AppProjectsProjectEpisodesEpisodeVideoLazyRoute,
    AppProjectsProjectEpisodesEpisodeIndexLazyRoute:
      AppProjectsProjectEpisodesEpisodeIndexLazyRoute,
  }

const AppProjectsProjectEpisodesRouteWithChildren =
  AppProjectsProjectEpisodesRoute._addFileChildren(
    AppProjectsProjectEpisodesRouteChildren,
  )

interface AppRouteChildren {
  AppAccessUnavailableRoute: typeof AppAccessUnavailableRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppPaymentReturnRoute: typeof AppPaymentReturnRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectAssistantRoute: typeof AppProjectsProjectAssistantRoute
  AppProjectsProjectEpisodesRoute: typeof AppProjectsProjectEpisodesRouteWithChildren
  AppProjectsProjectIngestRoute: typeof AppProjectsProjectIngestRoute
  AppProjectsProjectStylesRoute: typeof AppProjectsProjectStylesRoute
  AppProjectsProjectTasksRoute: typeof AppProjectsProjectTasksRoute
  AppProjectsProjectCharactersLazyRoute: typeof AppProjectsProjectCharactersLazyRoute
  AppProjectsProjectFreezoneLazyRoute: typeof AppProjectsProjectFreezoneLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessUnavailableRoute: AppAccessUnavailableRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppPaymentReturnRoute: AppPaymentReturnRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectAssistantRoute: AppProjectsProjectAssistantRoute,
  AppProjectsProjectEpisodesRoute: AppProjectsProjectEpisodesRouteWithChildren,
  AppProjectsProjectIngestRoute: AppProjectsProjectIngestRoute,
  AppProjectsProjectStylesRoute: AppProjectsProjectStylesRoute,
  AppProjectsProjectTasksRoute: AppProjectsProjectTasksRoute,
  AppProjectsProjectCharactersLazyRoute: AppProjectsProjectCharactersLazyRoute,
  AppProjectsProjectFreezoneLazyRoute: AppProjectsProjectFreezoneLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  RechargeRoute: RechargeRoute,
  DownloadLazyRoute: DownloadLazyRoute,
  PrototypesXialiaoDeskRoute: PrototypesXialiaoDeskRoute,
  WatchWorkRoute: WatchWorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
